# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GPFit <- function(y_train, X_train, X_test, K_train, K_test, sigma_sq, sigma_sq_mu, lambda, rate_tau, shape_tau, nburn, nthin, nsave, update_sigma_sq_mu, update_lambda) {
    .Call('_GPBart_GPFit', PACKAGE = 'GPBart', y_train, X_train, X_test, K_train, K_test, sigma_sq, sigma_sq_mu, lambda, rate_tau, shape_tau, nburn, nthin, nsave, update_sigma_sq_mu, update_lambda)
}

TreeCompress <- function(alpha, beta, cov_select, X) {
    .Call('_GPBart_TreeCompress', PACKAGE = 'GPBart', alpha, beta, cov_select, X)
}

rcpp_hello_world <- function() {
    .Call('_GPBart_rcpp_hello_world', PACKAGE = 'GPBart')
}

GetRankKernCat <- function(ranks, cats) {
    .Call('_GPBart_GetRankKernCat', PACKAGE = 'GPBart', ranks, cats)
}

GetRankKern <- function(ranks) {
    .Call('_GPBart_GetRankKern', PACKAGE = 'GPBart', ranks)
}

test_const_ref <- function(m) {
    invisible(.Call('_GPBart_test_const_ref', PACKAGE = 'GPBart', m))
}

log_sum_exp <- function(x) {
    .Call('_GPBart_log_sum_exp', PACKAGE = 'GPBart', x)
}

