---
title: "DPMs for Mediation"
author: "Antonio R. Linero"
date: "2023-09-13"
output: html_document
editor_options: 
  markdown: 
    wrap: 80
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r install, eval = FALSE}
str_dppack <- stringr::str_c("https://cran.r-project.org/src/contrib/",
                    "Archive/DPpackage/DPpackage_1.1-7.4.tar.gz")

devtools::install_github("lit777/BNPMediation")
devtools::install_url(str_dppack)
install.packages("mnormt")
```

```{r setup, results='hide'}
library(tidyverse)
library(CausalBNPBook)
library(DPpackage)
library(BNPMediation)
```

```{r gen_data}
make_data <- function(N = 200) {
  X <- rnorm(N)
  A <- rbinom(n = N, size = 1, prob = plogis(X))
  M <- X + A + rgamma(N, 2, 2)
  Y <- X + M + rgamma(N, 1, 1)
  df <- data.frame(Y = Y, M = M, A = A, X = X)
  return(df)
}

my_data <- as.matrix(make_data())

plot(as.data.frame(my_data))
```

```{r getdata}
w_0 <- my_data[my_data[,3] == 0, -3]
w_1 <- my_data[my_data[,3] == 1, -3]
```

```{r dpm_fit}
nburn <- 5000
nsave <- 5000
nskip <- 1
ndisplay <- 1000

mcmc <- list(nburn = nburn, nsave = nsave, nskip = nskip, ndisplay = ndisplay)
prior_1 <- list(alpha = 1, m1 = rep(0,3), psiinv2 = diag(3), nu1 = 6, nu2 = 6, 
                tau1 = 1, tau2 = 100)

fit_dpm_0 <- DPdensity(w_0, prior = prior_1, mcmc = mcmc, status = TRUE)
fit_dpm_1 <- DPdensity(w_1, prior = prior_1, mcmc = mcmc, status = TRUE)
```

```{r medresults}
bnpmediation(fit_dpm_1, fit_dpm_0, q = 3, n1 = nrow(w_1), n0 = nrow(w_0))
```
