---
title: "DPMs for Mediation"
author: "Antonio R. Linero"
date: "2023-09-13"
output: html_document
editor_options: 
  markdown: 
    wrap: 80
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r install, eval = FALSE}
str_dppack <- stringr::str_c("https://cran.r-project.org/src/contrib/",
                    "Archive/DPpackage/DPpackage_1.1-6.tar.gz")
devtools::install_github("lit777/BNPMediation")
devtools::install_url(str_dppack)
install.packages("mnormt")
install.packages("sn")
```

```{r setup, results='hide'}
library(tidyverse)
library(CausalBNPBook)
library(DPpackage)
library(BNPMediation)
library(sn)
```

```{r gen_data}
make_data <- function(N = 240) {
  A <- rbinom(N, 1, 0.5)
  X1 <- rnorm(N, 42.25, 9.61)
  X2 <- rnorm(N, 28.55, 5.56)
  M <- rsn(N, 0.2 + 0.2*A + 0.01*X1 + 0.01*X2, omega=1, alpha=7)
  
  step <- function(x,knot){
    ifelse(x>knot, x-knot, 0)
  }

  Y <- rnorm(N, 5 + 2.5*A + 0.2*step(M, 1.7) + 1*M^2 + 0.01*X1 + 0.01*X2, 0.2)
  
  df <- data.frame(Y = Y, M = M, A = A, X1 = X1, X2 = X2)
  return(df)
}

my_data <- as.matrix(make_data())

w_0 <- my_data[my_data[, 3] == 0, -3]
w_1 <- my_data[my_data[, 3] == 1, -3]
```

---

```{r, eval = FALSE}
Y <- my_data[,"Y"]
Z <- my_data[,"A"]
W1 <- my_data[,"X1"]
W2 <- my_data[,"X2"]
M <- my_data[,"M"]

#-------- Setting Variables
y0 <- Y[which(Z==0)]
y1 <- Y[which(Z==1)]
m0 <- M[which(Z==0)]
m1 <- M[which(Z==1)]
x1_0 <- W1[which(Z==0)];x2_0 <- W2[which(Z==0)]
x1_1 <- W1[which(Z==1)];x2_1 <- W2[which(Z==1)]
v1 <- cbind(m1,x1_1,x2_1)
v0 <- cbind(m0,x1_0,x2_0)
n0 <- length(y0)
n1 <- length(y1)

RANGE <- function(x){
    result <- (range(x)[2]-range(x)[1])^2/16
}


#------ Initial State
state <- NULL

#------ Prior information
w <- cbind(y1,v1)
wbar <- apply(w,2,median)
wcov <- diag(c(RANGE(y1), RANGE(m1), RANGE(x1_1), RANGE(x2_1)),4,4)
prior <- list(a0=1,b0=0.3,nu1=10,nu2=10,s2=wcov,m2=wbar,psiinv2=2*solve(wcov),tau1=6,tau2=3)

#------ Initial State
state <- NULL

#------ MCMC parameters
mcmc <- list(nburn=30000,nsave=2000,nskip=4,ndisplay=500)

#------ Fitting the Model for the Joinst Distribution under Z=1
fit.a.1 <- DPdensity(y=w,prior=prior,mcmc=mcmc,state=state,status=TRUE, na.action=na.omit)

#------ Prior information
w <- cbind(y0,v0)
wbar <- apply(w,2,median)
wcov <- diag(c(RANGE(y0), RANGE(m0), RANGE(x1_0), RANGE(x2_0)),4,4)
prior <- list(a0=1,b0=0.3,nu1=10,nu2=10,s2=wcov,m2=wbar,psiinv2=2*solve(wcov),tau1=6,tau2=3)

#------ Fitting the Model for the Joinst Distribution under Z=0
fit.a.0 <- DPdensity(y=w,prior=prior,mcmc=mcmc,state=state,status=TRUE, na.action=na.omit)


#------ Main Function
model1 <- bnpmediation(fit.a.1, fit.a.0, 7, NN = 100, n1=fit.a.1$nrec, n0=fit.a.0$nrec, extra.thin = 5)

#------- Results under S.I.
model1$ENIE;   model1$ENDE;   model1$ETE
model1$IE.c.i; model1$DE.c.i; model1$TE.c.i
```




```{r getdata}
w_0 <- my_data[my_data[,3] == 0, -3]
w_1 <- my_data[my_data[,3] == 1, -3]
```

```{r dpm_fit}
nburn <- 5000
nsave <- 5000
nskip <- 1
ndisplay <- 1000

mcmc <- list(nburn = nburn, nsave = nsave, nskip = nskip, ndisplay = ndisplay)
prior_1 <- list(alpha = 1, m1 = rep(0,3), psiinv2 = diag(3), nu1 = 6, nu2 = 6, 
                tau1 = 1, tau2 = 100)

fit_dpm_0 <- DPdensity(w_0, prior = prior_1, mcmc = mcmc, status = TRUE)
fit_dpm_1 <- DPdensity(w_1, prior = prior_1, mcmc = mcmc, status = TRUE)
```

```{r medresults}
bnpmediation(fit_dpm_1, fit_dpm_0, q = 3, n1 = nrow(w_1), n0 = nrow(w_0))
```
